# -*- coding: utf-8 -*-
"""
Teknik Sözlük — çıktıda geçen kısaltmalar ve sistem mühendisliği / radar terimleri.
Arayüz.py buradan okur (sozluk.SOZLUK). Bu dosyayı silersen Sözlük butonu
kendini devre dışı bırakır, uygulama çalışmaya devam eder.

Her madde 4'lüdür:
    (terim, açıklama_TR, açıklama_EN, [arama_kelimeleri])
'arama_kelimeleri' listesi, üretilen dokümanda bu terimin geçip geçmediğini
tespit etmek için kullanılır ("Bu çıktıda geçen terimler" bölümü).
"""

SOZLUK = {
    "V-Model Doküman Türleri": [
        ("UR — Kullanıcı Gereksinimi",
         "User Requirement. Kullanıcının/müşterinin sistemden beklentisini üst seviyede tanımlar. V-Model'in sol bacağının en üstündedir.",
         "User Requirement. Defines what the customer expects from the system at the highest level. Top of the V-Model left leg.",
         ["UR-", "Kullanıcı Gereksinimi", "User Requirement"]),
        ("SR — Sistem Gereksinimi",
         "System Requirement. Kullanıcı gereksinimini, sistemin ne yapması gerektiğini tanımlayan teknik ifadeye indirger.",
         "System Requirement. Refines a user requirement into a technical statement of what the system must do.",
         ["SR-", "Sistem Gereksinimi", "System Requirement"]),
        ("SSR — Alt Sistem Gereksinimi",
         "Subsystem Requirement. Sistem gereksinimini donanım/yazılım seviyesinde somut kısıtlara (işlemci, süre, frekans vb.) indirger.",
         "Subsystem Requirement. Refines a system requirement into concrete hardware/software constraints.",
         ["SSR-", "Alt Sistem Gereksinim"]),
        ("AT — Kabul Testi",
         "Acceptance Test. Bir Kullanıcı Gereksinimini doğrulayan test senaryosu. UR ile eşleşir.",
         "Acceptance Test. A test scenario that verifies a User Requirement.",
         ["AT-", "Kabul Testi", "Acceptance Test"]),
        ("SITET — Sistem Testi",
         "System Test. Bir Sistem Gereksinimini doğrulayan test senaryosu. SR ile eşleşir.",
         "System Test. A test scenario that verifies a System Requirement.",
         ["SITET-", "Sistem Testi", "System Test"]),
        ("SST — Alt Sistem Testi",
         "Subsystem Test. Bir Alt Sistem Gereksinimini doğrulayan, ölçülebilir Geçti/Kaldı kriteri içeren test.",
         "Subsystem Test. Verifies a Subsystem Requirement with a measurable Pass/Fail criterion.",
         ["SST-", "Alt Sistem Testi", "Subsystem Test"]),
    ],
    "Gereksinim Mühendisliği": [
        ("DSB — Daha Sonra Belirlenecek",
         "Bir değerin (süre, ölçü, sayı) kaynakta belli olmadığı durumda, o DEĞERİN YERİNE yazılan işaret. Yalnızca değer yer tutucusudur; standart adı, sıfat veya başka bir şey DEĞİLDİR. Örn: 'DSB saniye içinde'.",
         "'To Be Determined'. A placeholder written IN PLACE OF a value when the source doesn't specify it. Only a value placeholder. E.g. 'within DSB seconds'.",
         ["DSB"]),
        ("İzlenebilirlik (Traceability)",
         "Her gereksinimin nereden türediğinin (yukarı) ve nasıl doğrulandığının (aşağı) takip edilebilmesi. V-Model'in iki bacağını yatay olarak bağlar.",
         "The ability to trace each requirement to its source (upward) and to its verification (downward).",
         ["izlenebilir", "traceab"]),
        ("Atomiklik (Atomicity)",
         "Bir gereksinimin tek bir ihtiyacı ifade etmesi. Birden fazla ihtiyaç içeren madde test edilemez ve bölünmelidir.",
         "A requirement expressing a single need. An item with multiple needs must be split.",
         ["atomik", "atomic"]),
        ("GEÇTİ KRİTERİ (Pass Criterion)",
         "Bir testin başarılı sayılması için sağlanması gereken ölçülebilir eşik. Örn: 'işleme süresi < 3 sn'.",
         "The measurable threshold a test must meet to pass. E.g. 'processing time < 3 s'.",
         ["GEÇTİ KRİTERİ", "Pass Criterion", "Pass/Fail"]),
        ("Shall (Zorunluluk kipi)",
         "Gereksinim cümlelerinde zorunluluğu belirten kip. Türkçede '-malı/-meli/-dır'. Zorunlu olmayan ifadeler gereksinimi zayıflatır.",
         "The modal expressing obligation in requirement sentences ('shall').",
         ["shall", "malıdır", "melidir"]),
        ("Değişiklik Etki Analizi",
         "Change Impact Analysis. Bir madde değiştiğinde ona bağlı alt madde ve testlerin de gözden geçirilmesi/yeniden üretilmesi.",
         "Change Impact Analysis. When an item changes, its dependent items and tests are reviewed/regenerated.",
         ["etki analizi", "impact analysis"]),
    ],
    "Standart ve Araçlar": [
        ("V-Model",
         "Gereksinimlerin (sol bacak) her seviyede karşılık gelen bir doğrulama testiyle (sağ bacak) eşleştiği yaşam döngüsü modeli.",
         "A lifecycle model where requirements (left leg) match a verification test (right leg) at each level.",
         ["V-Model", "V Model"]),
        ("INCOSE",
         "International Council on Systems Engineering. Sistem mühendisliğinde dünya çapında kabul gören ilke ve iyi gereksinim yazım kurallarını belirleyen kuruluş.",
         "International Council on Systems Engineering. The globally recognized systems-engineering body.",
         ["INCOSE"]),
        ("DOORS",
         "Dynamic Object-Oriented Requirements System. Gereksinimleri veritabanı mantığıyla saklayan, izlenebilirlik ve etki analizi sunan araç.",
         "Dynamic Object-Oriented Requirements System. A requirements tool with traceability and impact analysis.",
         ["DOORS"]),
        ("MIL-STD",
         "Amerikan askeri standartları (Military Standard). Örn: MIL-STD-810 çevresel dayanım, MIL-STD-461 elektromanyetik uyumluluk.",
         "US Military Standards. E.g. MIL-STD-810 environmental, MIL-STD-461 EMC.",
         ["MIL-STD", "MIL STD"]),
        ("IP65 (Koruma Sınıfı)",
         "Ingress Protection. IP6X toza tam kapalı, IPX5 her yönden su püskürtmesine dayanıklı anlamına gelir.",
         "Ingress Protection rating. IP6X: dust-tight; IPX5: protected against water jets.",
         ["IP65", "IP6", "koruma sınıf"]),
    ],
    "Radar ve Sinyal İşleme": [
        ("Pasif Radar",
         "Kendi sinyalini yaymayan; ortamdaki mevcut yayınları (FM, DVB-T, GSM) 'aydınlatıcı' olarak kullanıp hedeften yansıyan sinyali işleyen radar. Konumunu ele vermez.",
         "A radar that emits no signal of its own; it uses existing broadcasts (FM, DVB-T, GSM) as illuminators and processes target reflections. Does not reveal its position.",
         ["pasif radar", "passive radar"]),
        ("Bistatik (Bistatic)",
         "Verici ile alıcının fiziksel olarak ayrı konumlarda bulunduğu radar geometrisi. Bistatik menzil = verici-hedef + hedef-alıcı mesafesi.",
         "Radar geometry where transmitter and receiver are at separate locations. Bistatic range = Tx-target + target-Rx distance.",
         ["bistatik", "bistatic"]),
        ("Doppler / Doppler Kayması",
         "Hareketli bir hedeften yansıyan sinyalin frekansındaki kayma. Hedefin bağıl hızını verir: f_D = (2·v/λ) (monostatik).",
         "The frequency shift of a signal reflected from a moving target, giving its relative velocity: f_D = (2·v/λ).",
         ["Doppler"]),
        ("TDOA (Varış Zamanı Farkı)",
         "Time Difference of Arrival. Referans ve gözetleme kanalları arasındaki zaman farkından bistatik menzil hesaplanır.",
         "Time Difference of Arrival. Bistatic range is computed from the time offset between reference and surveillance channels.",
         ["TDOA", "varış zaman"]),
        ("FDOA (Varış Frekansı Farkı)",
         "Frequency Difference of Arrival. Kanallar arası frekans farkından hedefin Doppler/hız bilgisi çıkarılır.",
         "Frequency Difference of Arrival. Target Doppler/velocity is derived from the frequency offset between channels.",
         ["FDOA", "varış frekans"]),
        ("Çapraz Belirsizlik Fonksiyonu",
         "Cross-Ambiguity Function (CAF). Referans ve gözetleme sinyalleri arasında menzil (gecikme) ve Doppler ekseninde korelasyon; pasif radarın temel tespit çıktısı.",
         "Cross-Ambiguity Function. Correlation of reference and surveillance signals over range (delay) and Doppler; the core detection output of a passive radar.",
         ["belirsizlik fonksiyon", "ambiguity", "CAF"]),
        ("Referans / Gözetleme Kanalı",
         "Pasif radarda aydınlatıcıya yönelen anten referans kanalını, hedef bölgesine yönelen anten gözetleme (surveillance) kanalını oluşturur.",
         "In passive radar, the antenna pointed at the illuminator forms the reference channel; the one pointed at the target zone forms the surveillance channel.",
         ["referans kanal", "gözetleme kanal", "surveillance", "reference channel"]),
        ("CLEAN / Doğrudan Sinyal Bastırma",
         "Gözetleme kanalındaki güçlü doğrudan yol (aydınlatıcı) ve çok yollu bileşenlerin uyarlamalı filtrelerle bastırılması; zayıf hedef yankısını ortaya çıkarır.",
         "Suppression of the strong direct-path (illuminator) and multipath components in the surveillance channel via adaptive filters, revealing the weak target echo.",
         ["CLEAN", "doğrudan sinyal", "direct signal", "çok yollu", "multipath"]),
        ("Radar Kesit Alanı (RCS)",
         "Radar Cross Section. Bir hedefin radar dalgasını ne kadar güçlü yansıttığının ölçüsü (m²). Geometri, malzeme ve bakış açısına bağlıdır.",
         "Radar Cross Section. A measure of how strongly a target reflects radar waves (m²). Depends on geometry, material and aspect angle.",
         ["RCS", "kesit alan", "cross section"]),
        ("Dinamik Aralık",
         "Dynamic Range. Alıcının aynı anda işleyebildiği en zayıf ve en güçlü sinyal arasındaki oran (dB). Pasif radarda kritiktir.",
         "Dynamic Range. The ratio (dB) between the weakest and strongest signals a receiver can handle simultaneously. Critical for passive radar.",
         ["dinamik aralık", "dynamic range"]),
        ("Hüzme Oluşturma (Beamforming)",
         "Anten dizisi elemanlarının faz/genlik ağırlıklandırılmasıyla hüzmenin elektronik olarak yönlendirilmesi; geliş açısı (DOA) kestirimi sağlar.",
         "Electronic steering of the beam by phase/amplitude weighting of array elements; enables direction-of-arrival (DOA) estimation.",
         ["hüzme", "beamform", "geliş açısı", "DOA"]),
        ("SNR (Sinyal-Gürültü Oranı)",
         "Signal-to-Noise Ratio. Faydalı sinyalin gürültüye oranı (dB). Tespit performansını doğrudan belirler.",
         "Signal-to-Noise Ratio (dB). Directly determines detection performance.",
         ["SNR", "sinyal-gürültü", "sinyal gürültü"]),
        ("İntegrasyon Süresi (CPI)",
         "Coherent Processing Interval. Sinyalin tutarlı (coherent) olarak birikimlendiği süre; uzun CPI zayıf hedefte SNR'yi artırır ama Doppler çözünürlüğünü ve gecikmeyi etkiler.",
         "Coherent Processing Interval. Longer CPI improves SNR for weak targets but affects Doppler resolution and latency.",
         ["integrasyon süre", "entegrasyon süre", "CPI", "coherent"]),
    ],
}
